### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by rapgro** [mhogomchungu/lxqt_wallet#2] opened 2016-07-23 16:35 UTC
Compiled qm files should be generated via cmake from the ts files. Please provide ts files only.
Further, naming for those files is incorrect, two letters only allowed for each of both language and country codes, separated with an underscore ('_').
https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html
https://www.gnu.org/software/gettext/manual/html_node/Usual-Language-Codes.html
https://www.gnu.org/software/gettext/manual/html_node/Country-Codes.html

dutch_NL >  nl_NL
french_FR > fr_FR
german_DE > de_DE
greek_GR > gr_GR
spanish_ES > es_ES

For correct cmake integration:
http://stackoverflow.com/questions/19193121/automated-translation-management-with-cmake-and-qt5
http://stackoverflow.com/questions/24095800/qt-internationalization-and-cmake-how-to-update-ts-and-dont-lose-them

I wonder, for what is that pro file in top folder? Either use qmake or cmake with qt extensions.

**Comment by mhogomchungu** [comment] 2016-07-23 18:40
The "lxqt_wallet.pro" file is used by lupdate tool to extract translatable strings from source files and store them in .ts files for translation.

The build system uses cmake,anything else is unsupported.

**Comment by rapgro** [comment] 2016-07-23 21:05
This works for me:

1) rename files:

```
rm -rv translations.qm
mv translations.ts translations
mv translations/dutch_NL.ts translations/nl_NL.ts
mv translations/french_FR.ts translations/fr_FR.ts
mv translations/german_DE.ts translations/de_DE.ts
mv translations/greek_GR.ts translations/gr_GR.ts
mv translations/spanish_ES.ts translations/es_ES.ts
```

2) patch:

```
--- a/frontend/CMakeLists.txt   2016-07-23 20:22:27.836650136 +0200
+++ b/frontend/CMakeLists.txt   2016-07-23 20:24:47.691726914 +0200
@@ -283,11 +283,18 @@
    TARGET_LINK_LIBRARIES(lxqtwallet "${link_libraries}" lxqtwallet-backend ${QT_LIBRARIES} )
 endif()

-install( FILES ../translations.qm/german_DE.qm   DESTINATION share/lxqt_wallet/translations.qm/ )
-install( FILES ../translations.qm/greek_GR.qm    DESTINATION share/lxqt_wallet/translations.qm/ )
-install( FILES ../translations.qm/dutch_NL.qm    DESTINATION share/lxqt_wallet/translations.qm/ )
-install( FILES ../translations.qm/french_FR.qm   DESTINATION share/lxqt_wallet/translations.qm/ )
-install( FILES ../translations.qm/spanish_ES.qm   DESTINATION share/lxqt_wallet/translations.qm/ )
+SET(TRANSLATIONS
+   ../translations/nl_NL.ts
+   ../translations/fr_FR.ts
+   ../translations/de_DE.ts
+   ../translations/gr_GR.ts
+   ../translations/es_ES.ts
+)
+
+FIND_PACKAGE(Qt5LinguistTools)
+QT5_ADD_TRANSLATION(QM_FILES ${TRANSLATIONS})
+SET(QM_FILES ${QM_FILES} PARENT_SCOPE)
+ADD_CUSTOM_TARGET (translations ALL DEPENDS ${QM_FILES})

 if(BUILD_SHARED)
    install(TARGETS lxqtwallet RUNTIME LIBRARY DESTINATION "${LIB_PATH}")
```

**Comment by mhogomchungu** [comment] 2016-07-24 02:59
Did you try to install the project with your patch? Those .qm files do not get installed,or rather,they didnt get installed here with "make install".

I made a few changes to your patch and they resulted in this commit: https://github.com/mhogomchungu/lxqt_wallet/commit/016e8b9ce378ec21567c4d80c9fd4b0d7a120a99

Looking around my system and lxqt's .qm files seems to be installed at:
`INSTALL_PREFIX/share/lxqt/translations/PROJECT-NAME/` and they are in a format of `PROJECT-NAME_file.qm`

**Comment by mhogomchungu** [comment] 2016-08-01 16:40
closing this one since the issue is now resolved.

**Closed as completed by mhogomchungu** 2016-08-01 16:40 UTC

**Comment by rapgro** [comment] 2016-08-04 16:27
Thanks, it seems now to work correctly.
